server:
  port: 8888
spring:
  application:
    name: java-concurrency-with-spring

  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root   # MySQL ????
    password: 3867   # ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? ??: create, create-drop, update / ?? ??: validate ??
    show-sql: true       # SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true # SQL ?? ?? ??
    database-platform: org.hibernate.dialect.MySQL8Dialect
